### ISSUE TITLE
Fails to Compile with Ecto 3.0

### ISSUE THREAD

**Issue by juddey** [promptworks/guardian_trackable#4]
Hello! 

Upgrading to Ecto 3.0 gives me this:

```
==> guardian_trackable
Compiling 3 files (.ex)

== Compilation error in file lib/mix/tasks/guardian_trackable.install.ex ==
** (CompileError) lib/mix/tasks/guardian_trackable.install.ex:39: undefined function migrations_path/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :guardian_trackable, "mix compile" failed. You can recompile this dependency with "mix deps.compile guardian_trackable", update it with "mix deps.update guardian_trackable" or clean it with "mix deps.clean guardian_trackable
```

Running with a fork right now, but wondered if you were interested in a PR. Cheers.

**Comment by rzane** [comment]
I'd happily accept a PR!

**Comment by rzane** [comment]
I don't think so. I don't expect to add any new features here, so people using 2.x can continue to use the current version. But, we should remember to bump the Ecto requirement in mix.exs.

**Comment by juddey** [comment]
Coolio, I'll put it on my "to-do" list to finish off and send your way.

**Comment by rzane** [comment]
Yeah, I can't imagine anyone needing microseconds for this purpose. I think if we can probably just fix the test.
